openapi: 3.0.2
info:
  title: Rest API
  version: "1.0.1"
paths:
  /v1/directories:
    get:
      summary: List directory
      operationId: app.controllers.object_controller.list_directory
      parameters:
        - name: prefixPath
          in: query
          schema:
            type: string
          required: true
      tags:
        - Directory
      responses:
        "200":
          description: object response
          content:
            application/json:
              schema:
                type: object
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    post:
      summary: create directory
      operationId: app.controllers.object_controller.create_directory
      tags:
        - Directory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: object response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    put:
      summary: Rename directory
      operationId: app.controllers.object_controller.rename_directory
      tags:
        - Directory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: object response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    delete:
      summary: Delete directory
      operationId: app.controllers.object_controller.delete_directory
      tags:
        - Directory
      parameters:
        - name: prefixPath
          in: query
          schema:
            type: string
          required: true
      responses:
        "204":
          description: object response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
  /v1/objects:
    post:
      summary: Upload blob
      operationId: app.controllers.object_controller.create_object
      tags:
        - Object
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
      parameters:
        - name: objectPath
          in: query
          schema:
            type: string
          required: true
      responses:
        "200":
          description: object response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    get:
      summary: Get blob
      operationId: app.controllers.object_controller.get_object
      tags:
        - Object
      parameters:
        - name: objectPath
          in: query
          schema:
            type: string
          required: true
      responses:
        "200":
          description: object response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    delete:
      summary: Delete blob
      operationId: app.controllers.object_controller.delete_object
      tags:
        - Object
      parameters:
        - name: objectPath
          in: query
          schema:
            type: string
          required: true
      responses:
        "204":
          description: object response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    put:
      summary: Rename blob
      operationId: app.controllers.object_controller.rename_object
      tags:
        - Object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: object response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
components:
  responses:
    InternalError: 
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
    Conflict:
      description: resource are already exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
    Unauthorized: 
      description: No Permissions to perform action
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
    NotFound: 
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
  schemas:
    object_response:
      description: object response
      type: object
      properties:
        status:
          type: integer
        success:
          type: boolean
    generic_message_response:
      description: generic json response with message property
      type: object
      required: 
        - message
      properties:
        message:
          type: string
    generic_error_response:
      description: generic json error response
      type: object
      required: 
        - message
        - code
        - status
      properties:
        message:
          type: string
        code:
          type: integer
          enum: [400, 401, 403, 404, 409, 500]
        status:
          type: string