openapi: 3.0.2
info:
  title: Extended Object Storage Rest API
  version: "1.0.1"
  description: "Extended object storage - final project for Big Data Platform course - Reichman University 2022"
externalDocs:
  description: "Project's Github"
  url: "https://github.com/talkapi/Extended-Object-Storage"
paths:
  /v1/directories:
    get:
      summary: List directory
      operationId: app.controllers.object_controller.list_directory
      parameters:
        - name: prefixPath
          description: 'Directory path'
          example: "/dir/dir1"
          in: query
          schema:
            type: string
          required: true
      tags:
        - Directory
      responses:
        "200":
          description: List directory response
          content:
            application/json:
              schema:
                description: List directory response
                type: object
                properties:
                  response:
                    type: array
                    items:
                      type: string
                  status:
                      type: integer
                      enum: [200]
                  success:
                      type: boolean
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    post:
      summary: create directory
      operationId: app.controllers.object_controller.create_directory
      tags:
        - Directory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                  description: 'Directory path'
                  example: '/dir'
      responses:
        "200":
          description: Generic response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    put:
      summary: Rename directory
      operationId: app.controllers.object_controller.rename_directory
      tags:
        - Directory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dirPath:
                  type: string
                  description: 'Directory path'
                newDirPath:
                  type: string
                  description: 'Directory new path'
      responses:
        "200":
          description: object response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    delete:
      summary: Delete directory
      operationId: app.controllers.object_controller.delete_directory
      tags:
        - Directory
      parameters:
        - name: prefixPath
          in: query
          description: 'Directory path'
          example: "/dir/dir1"
          schema:
            type: string
          required: true
      responses:
        "204":
          description: object response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
  /v1/objects:
    post:
      summary: Create object
      operationId: app.controllers.object_controller.create_object
      tags:
        - Object
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      parameters:
        - name: objectPath
          in: query
          description: "Full path to object"
          example: "/dir/file.csv"
          schema:
            type: string
          required: true
      responses:
        "200":
          description: Generic response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    get:
      summary: Get Object
      operationId: app.controllers.object_controller.get_object
      tags:
        - Object
      parameters:
        - name: objectPath
          in: query
          description: "Full path to object"
          example: "/dir/file.csv"
          schema:
            type: string
          required: true
      responses:
        "200":
          description: object response
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    contentType:
                      type: string
                    object:
                      type: string
                    status:
                      type: integer
                      enum: [200]
                    success:
                      type: boolean
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    delete:
      summary: Delete Object
      operationId: app.controllers.object_controller.delete_object
      tags:
        - Object
      parameters:
        - name: objectPath
          in: query
          example: "/dir/file.csv"
          schema:
            type: string
          required: true
      responses:
        "204":
          description: No content
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
    put:
      summary: Rename Object
      operationId: app.controllers.object_controller.rename_object
      tags:
        - Object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                objectPath:
                  type: string
                  description: 'Full path to object'
                  example: "/dir/file.csv"
                newObjectName:
                  type: string
                  description: 'New object name'
                  example: "file1.csv"
      responses:
        "200":
          description: Generic response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/generic_response'
        "400":
          $ref: '#/components/responses/BadRequest'
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/InternalError'
components:
  responses:
    InternalError: 
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
    Conflict:
      description: resource are already exists
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
    Unauthorized: 
      description: No Permissions to perform action
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
    NotFound: 
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generic_error_response'
  schemas:
    generic_response:
      description: object response
      type: object
      properties:
        status:
          type: integer
          enum: [200]
        success:
          type: boolean
    object_response:
      description: object response
      type: object
      properties:
        contentType:
          type: string
        object:
          type: string
        status:
          type: integer
          enum: [200]
        success:
          type: boolean
    generic_error_response:
      description: generic json error response
      type: object
      required: 
        - reason
        - status
        - success
      properties:
        reason:
          type: string
        status:
          type: integer
          enum: [400, 401, 403, 404, 409, 500]
        success:
          type: boolean
          example: false